config/routes.rb
Rails.application.routes.draw do

  namespace :tasks do
  resources :messages, only: :index, defaults: { format: :json }
 end

  post 'like/:id' => 'likes#create', as: 'create_like'
  resources :tasks
  
  root 'homes#top'
  post 'tasks/:id' => 'tasks#edit'
  get 'taksks/:id' => 'tasks#show'
  get 'homes/guest_sign_in', to: 'homes#new_guest'
  
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	passwords: 'users/passwords'
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user, optional: true
	has_many :tasks, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user
	mount_uploader :image, ImageUploader

  def self.search(index)
    return Sumple.all() unless search
    Sumple.where('title LIKE(?)', "%#{index}%")
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  protect_from_forgery

  def index
  	@tasks = Task.all.page(params[:page]).per(10)
  end

  def show 
  	@task = Task.find(params[:id])
    @like = Like.new
  end
  

  def new
  	@task = Task.new
  end

  def create
    @task = current_user.tasks.new task_params
    @task.save!
    redirect_to @task
  end

  def edit
  	@task = Task.find(params[:id])
  end

  def update
  	@task = Task.find(params[:id])
  	@task.update(task_params)
  	redirect_to @task
  end

  def destroy
  	@task = Task.find(params[:id])
    @task.destroy
    flash[:sucess] = "削除します"
  	redirect_to tasks_url
  end

  private
  
  def task_params
  	params.require(:task).permit(:title, :description, :image)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

<div style="width: 300px;">
  <%= form_for(@task) do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, size: 50 %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
    </div>
    <%= f.submit '更新する' %>
  <% end %>
</div>
<p><%= link_to '一覧に戻る', tasks_path %></p>

app/views/tasks/form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>

<h1 class="text-center">新規作成</h1>
<h1 class="text-center">やるべきことを画像と共に記載しよう！</h1>

<p id="notice"><%= notice %></p>
<div class="contents">
  <%= text_field_tag :title,'', class: 'js-text_field', placeholder: 'タイトルを入力してください' %>


</div>

<table>
<tr>
    <th>Id</th><th>Title</th><th>Description</th>
  </tr>
  <% @tasks.each do |task| %>
  <tr>
    <td><%= task.id %></td>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= image_tag task.image.url, width: 100 %></td>
    <td><button class="bt01 btn-light"><%= button_to 'Show', task_path(task), method: :get %></td></button>
    <td><button class="bt02 btn-light"><%= button_to 'Edit', task_path(task) %></td></button>
    <td><button class="btn btn-danger"><%= button_to 'Delete', task_path(task), method: :delete, data: { confirm: "削除してもよろしいですか" } %></td></button>
    <% end %>
  </tr>
</table>
<%= paginate @tasks %>

<button type="button" class="btn btn-light"><%= link_to 'ToDoの作成', new_task_path %></button>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

<div style="width: 300px;">
  <%= form_for(@task) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, size: 50 %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  
    <%= f.submit '投稿する' %>
  <% end %>
</div>
<p><%= link_to '一覧に戻る', tasks_url %></p>

app/views/tasks/show.html.erb
<h1>画像詳細</h1>
<p>以下の内容で投稿されました</p>
<p id="notice"><%= notice %></p>
<table>
  <%= form_for(@task) do |f| %>
    <th>題名</th> <br>
    <th><%= @task.title %></th>
    <th>説明</th>
    <th><%= @task.description %></th>
  <tr>
    <th>User.Email</th>
    <td><%= @task.user.email %></td>
  </tr>
  <h3>いいね件数: <%= @task.likes.count %></h3>
  <% if current_user.already_liked?(@task) %>
    <%= button_to 'いいねを取り消す', like_path(@task), method: :delete %>
  <% else %>
    <%= button_to 'いいね', create_like_path, method: :post %>
  <% end %>

  <h2>いいねしたユーザー</h2>
  <% @task.liked_users.each do |user| %>
   <li><%= user.email %></li>
  <% end %>

  <td><%= image_tag (@task.image.url) if @task.image.present? %></td>
<% end %>

</table>
<p><%= link_to '一覧に戻る', tasks_path, method: :get %></p>